function(generate_legacy_storage_plan_entries OUTPUT_VARIABLE)
  set(PATHS "")
  set(SOURCE_PRESENT "")
  set(SOURCE_HASHES "")
  set(SOURCE_SIZES "")
  foreach(TARGET_VERSION 1.5.97 1.6.1170)
    set(MANIFEST_PATH
      "${PROJECT_SOURCE_DIR}/assets/runtime/1.7.104-to-${TARGET_VERSION}/manifest.json")
    if(NOT EXISTS "${MANIFEST_PATH}")
      message(FATAL_ERROR "The legacy storage catalog is missing: ${MANIFEST_PATH}")
    endif()
    file(READ "${MANIFEST_PATH}" MANIFEST_JSON)
    string(JSON FILE_COUNT LENGTH "${MANIFEST_JSON}" files)
    math(EXPR FILE_LAST "${FILE_COUNT} - 1")
    foreach(INDEX RANGE 0 ${FILE_LAST})
      string(JSON RELATIVE_PATH GET "${MANIFEST_JSON}" files ${INDEX} path)
      string(REPLACE "\\" "/" RELATIVE_PATH "${RELATIVE_PATH}")
      string(JSON PRESENT GET "${MANIFEST_JSON}" files ${INDEX} sourcePresent)
      string(JSON HASH GET "${MANIFEST_JSON}" files ${INDEX} sourceSha256)
      string(TOLOWER "${HASH}" HASH)
      string(JSON SIZE GET "${MANIFEST_JSON}" files ${INDEX} sourceSize)
      list(FIND PATHS "${RELATIVE_PATH}" EXISTING_INDEX)
      if(EXISTING_INDEX EQUAL -1)
        list(APPEND PATHS "${RELATIVE_PATH}")
        list(APPEND SOURCE_PRESENT "${PRESENT}")
        list(APPEND SOURCE_HASHES "${HASH}")
        list(APPEND SOURCE_SIZES "${SIZE}")
      else()
        list(GET SOURCE_PRESENT ${EXISTING_INDEX} EXISTING_PRESENT)
        list(GET SOURCE_HASHES ${EXISTING_INDEX} EXISTING_HASH)
        list(GET SOURCE_SIZES ${EXISTING_INDEX} EXISTING_SIZE)
        if(NOT PRESENT STREQUAL EXISTING_PRESENT OR
           NOT HASH STREQUAL EXISTING_HASH OR
           NOT SIZE STREQUAL EXISTING_SIZE)
          message(FATAL_ERROR
            "Legacy source metadata differs for ${RELATIVE_PATH}")
        endif()
      endif()
    endforeach()
  endforeach()

  set(ENTRIES "")
  list(LENGTH PATHS ENTRY_COUNT)
  math(EXPR ENTRY_LAST "${ENTRY_COUNT} - 1")
  foreach(INDEX RANGE 0 ${ENTRY_LAST})
    list(GET PATHS ${INDEX} RELATIVE_PATH)
    list(GET SOURCE_PRESENT ${INDEX} PRESENT)
    list(GET SOURCE_HASHES ${INDEX} HASH)
    list(GET SOURCE_SIZES ${INDEX} SIZE)
    if(PRESENT)
      set(PRESENT_CPP true)
    else()
      set(PRESENT_CPP false)
    endif()
    string(APPEND ENTRIES
      "    LegacyManagedFile{\"${RELATIVE_PATH}\", ${PRESENT_CPP}, \"${HASH}\", ${SIZE}ULL},\n")
  endforeach()
  set(${OUTPUT_VARIABLE} "${ENTRIES}" PARENT_SCOPE)
endfunction()
